/**
 * Domain types for the billing rails.
 *
 * Nothing here knows about organizations, plans, orders, or tiers — a payment
 * carries an opaque `reference` that the host application gives meaning to.
 * That is the whole portability story: map your own id into `reference` and
 * every rail settles the same way.
 */

/** Which payment rail a record belongs to. */
export type Rail = 'stk' | 'c2b' | 'b2c' | 'stripe'

/**
 * Three states, deliberately. Providers report a dozen failure modes between
 * them (cancelled, wrong PIN, insufficient funds, expired session); those are
 * kept verbatim in `failureCode` / `failureReason` rather than multiplied into
 * statuses the CAS guard would then have to reason about.
 */
export type PaymentStatus = 'PENDING' | 'SUCCESS' | 'FAILED'

export interface BillingPayment {
  /** Your internal id. Generated by the store adapter if you do not supply one. */
  id: string
  rail: Rail
  /**
   * Whatever the payment is *for*, in your system: an organization id, an
   * order number, a user id. Opaque to this package, indexed by the adapters,
   * and echoed back on every settlement.
   */
  reference: string
  /**
   * The provider's handle, unique per rail — CheckoutRequestID (STK),
   * TransID (C2B), ConversationID (B2C), or the Checkout session id (Stripe).
   * This is the webhook key and the deduplication key.
   */
  providerRef: string
  /** Decimal string; never a float. KES amounts from Daraja are whole numbers. */
  amount: string
  /** ISO-4217, lowercase for Stripe's sake ('kes', 'usd'). */
  currency: string
  status: PaymentStatus
  /** Who paid or was paid — an MSISDN for M-PESA, a customer id for Stripe. */
  payerRef?: string
  /** M-PESA receipt number, or the Stripe PaymentIntent id. */
  receipt?: string
  failureCode?: string
  failureReason?: string
  /** The full provider payload, for audit and for questions you have not thought of yet. */
  raw?: unknown
  createdAt: Date
  settledAt?: Date
}

/** What a webhook handler hands back to your framework binding. */
export interface WebhookReply {
  status: number
  body: unknown
}

/**
 * The outcome of handling one webhook delivery.
 *
 * `settled` is the record this delivery moved to a terminal state, or null
 * when the delivery was a duplicate, unknown, or informational. Anything you
 * do *because* a payment succeeded belongs behind a non-null `settled` —
 * that is what makes it exactly-once.
 */
export interface WebhookResult {
  reply: WebhookReply
  settled: BillingPayment | null
  duplicate: boolean
}

export type MpesaEnvironment = 'sandbox' | 'live'

export interface DarajaConfig {
  consumerKey: string
  consumerSecret: string
  /** Paybill or till number used for STK Push and C2B. */
  shortCode: string
  /** STK Push passkey from the Daraja portal. */
  passKey: string
  environment: MpesaEnvironment
  /** Public HTTPS origin of your app; callback URLs are built from it. */
  callbackBaseUrl: string
  /** Override the default callback paths if your routes live elsewhere. */
  callbackPaths?: Partial<CallbackPaths>
  /** B2C only — API operator username. */
  initiatorName?: string
  /** B2C only — operator password, encrypted per request. */
  initiatorPassword?: string
  /** B2C only — Safaricom's public certificate (PEM) for this environment. */
  securityCertificate?: string
  /** Per-request budget in ms. Default 30000. */
  timeoutMs?: number
}

export interface CallbackPaths {
  stkCallback: string
  c2bValidation: string
  c2bConfirmation: string
  b2cResult: string
  b2cTimeout: string
}

export const DEFAULT_CALLBACK_PATHS: CallbackPaths = {
  stkCallback: '/api/webhooks/mpesa',
  c2bValidation: '/api/webhooks/mpesa/c2b/validation',
  c2bConfirmation: '/api/webhooks/mpesa/c2b/confirmation',
  b2cResult: '/api/webhooks/mpesa/b2c/result',
  b2cTimeout: '/api/webhooks/mpesa/b2c/timeout',
}

export interface StripeConfig {
  secretKey: string
  /** Endpoint signing secret (whsec_…). Required to accept webhooks. */
  webhookSecret: string
  /** Reject signatures older than this many seconds. Default 300, as Stripe recommends. */
  toleranceSeconds?: number
  timeoutMs?: number
}

export interface Logger {
  info(msg: string, meta?: Record<string, unknown>): void
  warn(msg: string, meta?: Record<string, unknown>): void
  error(msg: string, meta?: Record<string, unknown>): void
}
